apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      args: ["10"]
      ## command serving as entrypoint in the docker file
      command: ["sleep2.0"]
      #args: ["10"]