apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: myapp
spec:
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color
    ports:
    - containerPort: 8080
## Inject all values from app-config as env variables 
    envFrom:
    - configMapRef:
      name: app-config
## Inject single env variables from app-config
    env:
    - name: APP_COLOR
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_COLOR
          
## Inject env variables as volume
    volumes:
    - name: app-config-volume
      configMapRef:
        name: app-config