# Secret data to be used in the secret_definition.yaml file
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
# data has to be base64-encoded
data:
  DB_Host: bXlzcWw=
  DB_User: cm9vdA==
  DB_Password: cGFzd3Jk