apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"
  # Determining Pod using Node Selector
  nodeSelector:
    size: Large
  # Using Node Affinity
  affinity:
    nodeAffniity:
      requiredDuringSchedulingIgnoredDuringExecution:
      # other Affinity Types: preferredDuringSchedulingIgnoreDuringExecution, requiredDuringSchedulingRequiredDuringExecution
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In
            values:
              -Large
            ## other operators: Exists, NotIn
